ctx.regex("NUMBER","-?[1-9](([0-9])*)")
ctx.regex("NUMBERPOS","[1-9](([0-9])*)")
ctx.regex("NUMBER_0TO1","(1)|0\.(([0-9])+)")
ctx.regex("STRING","[a-zA-Z]+")
ctx.regex("LOWSTRING","[a-z]+")
ctx.regex("TAG","[a-z1-9]+")
ctx.rule("TEXT","")
ctx.rule("TEXT","{STRING}")
ctx.rule("TEXT","{STRING} {TEXT}")
ctx.regex("IP","(([1-9][0-9]?[0-9]?)|0)\.(([1-9][0-9]?[0-9]?)|0)\.(([1-9][0-9]?[0-9]?)|0)\.(([1-9][0-9]?[0-9]?)|0)")
ctx.rule("HTTP_DATE","{WDAY}, {MDAY} {MONTH} {YEAR} {HOUR}:{MINUTE}:{SECOND} GMT")
ctx.rule("WDAY","Tue")
ctx.rule("WDAY","Mon")
ctx.rule("WDAY","Wed")
ctx.rule("WDAY","Thu")
ctx.rule("WDAY","Fri")
ctx.rule("WDAY","Sat")
ctx.rule("WDAY","Sun")
ctx.regex("MONTH","Jan")
ctx.regex("MONTH","Feb")
ctx.regex("MONTH","May")
ctx.regex("MONTH","Apr")
ctx.regex("MONTH","Mar")
ctx.regex("MONTH","Jun")
ctx.regex("MONTH","Jul")
ctx.regex("MONTH","Aug")
ctx.regex("MONTH","Oct")
ctx.regex("MONTH","Sep")
ctx.regex("MONTH","Nov")
ctx.regex("MONTH","Dec")
ctx.regex("MDAY","[0-3][0-9]")
ctx.regex("YEAR","[0-9][0-9][0-9][0-9]")
ctx.regex("HOUR","[0-2][0-9]")
ctx.regex("SECOND","[0-6][0-9]")
ctx.regex("MINUTE","[0-6][0-9]")
ctx.rule("START","{REQUEST}")
ctx.rule("REQUEST", "{REQUEST_LINE}\n{GENERAL_HEADER}{REQUEST_HEADER}\n")
#ctx.rule("REQUEST", "{REQUEST_LINE}\n{GENERAL_HEADER}{REQUEST_HEADER}{ENTITY_HEADER}{TEXT}\n")


ctx.rule("GENERAL_HEADER","{CACHE_CONTROL}{CONNECTION}{DATE}{PRAGMA}{TRAILER}{TRANSFER_ENCODING}{UPGRADE}{VIA}{WARNING}")
ctx.rule("REQUEST_HEADER","{ACCEPT}{ACCEPT_CHARSET}{ACCEPT_ENCODING}{ACCEPT_LANGUAGE}{AUTHORIZATION}{EXPECT}{FROM}{HOST}{IF_MATCH}{IF_MODIFIED_SINCE}{MAX_FORWARDS}{PROXY_AUTHORIZATION}{RANGE}{REFERER}{TE}{USER_AGENT}")
#ctx.rule("ENTITY_HEADER","{ALLOW}\n{CONTENT_ENCODING}\n{CONTENT_LANGUAGE}\n{CONTENT_LENGTH}\n{CONTENT_LOCATION}\n{CONTENT_MD5}\n{CONTENT_RANGE}\n{CONTENT_TYPE}\n{EXPIRES}\n{LAST_MODIFIED}")

# Request line, TODO weitere URI PATHS (auch absolute etc.)
ctx.rule("REQUEST_LINE","{METHOD} {REQUEST_URI} {HTTP_VERSION}")
ctx.rule("METHOD","OPTIONS")
ctx.rule("METHOD","GET")
ctx.rule("METHOD","HEAD")
ctx.rule("METHOD","POST")
ctx.rule("METHOD","PUT")
ctx.rule("METHOD","DELETE")
ctx.rule("METHOD","TRACE")
ctx.rule("METHOD","CONNECT")
ctx.rule("REQUEST_URI","/")
ctx.rule("REQUEST_URI","*")
ctx.rule("REQUEST_URI","/index.html")
ctx.rule("REQUEST_URI","/?{GET_OPTIONS}")
ctx.rule("REQUEST_URI","/index.html?{GET_OPTIONS}")
ctx.rule("GET_OPTIONS","")
ctx.rule("GET_OPTIONS","{STRING}={STRING}")
ctx.rule("GET_OPTIONS","{STRING}={STRING},{GET_OPTIONS}")
ctx.rule("HTTP_VERSION","HTTP/1.0")
ctx.rule("HTTP_VERSION","HTTP/1.1")
ctx.rule("HTTP_VERSION","HTTP/2")

# GENERAL header
ctx.rule("CACHE_CONTROL","")
ctx.rule("CACHE_CONTROL","Cache-Control: {CACHE_DIRECTIVE}\n")
ctx.rule("CACHE_DIRECTIVE","no-cache")
ctx.rule("CACHE_DIRECTIVE","no-store")
ctx.rule("CACHE_DIRECTIVE","max-age={NUMBER}")
ctx.rule("CACHE_DIRECTIVE","max-stale={NUMBER}")
ctx.rule("CACHE_DIRECTIVE","min-fresh={NUMBER}")
ctx.rule("CACHE_DIRECTIVE","no-transform")
ctx.rule("CACHE_DIRECTIVE","only-if-cached")
ctx.rule("CONNECTION","")
ctx.rule("CONNECTION","Connection: open\n")
ctx.rule("CONNECTION","Connection: close\n")
ctx.rule("DATE","")
ctx.rule("DATE","Date: {HTTP_DATE}\n")
ctx.rule("PRAGMA","")
ctx.rule("PRAGMA","Pragma: no-cache\n")
ctx.rule("TRAILER","")
ctx.rule("TRAILER","Trailer: {FIELD}")
ctx.rule("FIELD","Cache-Control\n")
ctx.rule("FIELD","Connection\n")
ctx.rule("FIELD","Date\n")
ctx.rule("FIELD","Pragma\n")
ctx.rule("FIELD","Upgrade\n")
ctx.rule("FIELD","Via\n")
ctx.rule("FIELD","Warning\n")
ctx.rule("FIELD","Accept\n")
ctx.rule("FIELD","Accept-Charset\n")
ctx.rule("FIELD","Accept-Encoding\n")
ctx.rule("FIELD","Accept-Language\n")
ctx.rule("FIELD","Authorization\n")
ctx.rule("FIELD","Expect\n")
ctx.rule("FIELD","From\n")
ctx.rule("FIELD","Host\n")
ctx.rule("FIELD","If-Match\n")
ctx.rule("FIELD","If-Modified-Since\n")
ctx.rule("FIELD","If-None-Match\n")
ctx.rule("FIELD","If-Range\n")
ctx.rule("FIELD","If-Unmodified-Since\n")
ctx.rule("FIELD","Max-Forwards\n")
ctx.rule("FIELD","Proxy-Authorization\n")
ctx.rule("FIELD","Range\n")
ctx.rule("FIELD","Referer\n")
ctx.rule("FIELD","TE\n")
ctx.rule("FIELD","User-Agent\n")
ctx.rule("TRANSFER_ENCODING","")
ctx.rule("TRANSFER_ENCODING","Transfer-Encoding: chunked\n")
ctx.rule("UPGRADE","")
ctx.rule("UPGRADE","Upgrade: {PRODUCT}\n")
ctx.rule("PRODUCT","")
ctx.rule("PRODUCT","HTTP/2.0")
ctx.rule("PRODUCT","libwww/2.17b3")
ctx.rule("PRODUCT","libwww/2.17b3, {PRODUCT}")
ctx.rule("PRODUCT","CERN-LineMode/2.15")
ctx.rule("PRODUCT","CERN-LineMode/2.15, {PRODUCT}")
ctx.rule("PRODUCT","HTTP/2.0, {PRODUCT}")
ctx.rule("PRODUCT","SHTTP/1.3")
ctx.rule("PRODUCT","SHTTP/1.3, {PRODUCT}")
ctx.rule("PRODUCT","IRC/6.9")
ctx.rule("PRODUCT","IRC/6.9, {PRODUCT}")
ctx.rule("PRODUCT","RTA/x11")
ctx.rule("PRODUCT","RTA/x11, {PRODUCT}")
ctx.rule("VIA","")
ctx.rule("VIA","Via: {HTTP_VERSION} {IP}:{NUMBER}\n")
ctx.rule("VIA","Via: {HTTP_VERSION} {IP}\n")
ctx.rule("WARNING","")
ctx.rule("WARNING",'Warning: 3DIGIT {IP} {TEXT} "{HTTP_DATE}"\n')
ctx.rule("WARNING",'Warning: 3DIGIT {IP}:{NUMBER} {TEXT} "{HTTP_DATE}"\n')
ctx.rule("WARNING","Warning: 3DIGIT {IP} {TEXT}\n")
ctx.rule("WARNING","Warning: 3DIGIT {IP}:{NUMBER} {TEXT}\n")


# request header
ctx.rule("ACCEPT","")
ctx.rule("ACCEPT","Accept: {MEDIA_RANGE}\n")
ctx.rule("MEDIA_RANGE","{TYPE}/{SUBTYPE}")
ctx.rule("MEDIA_RANGE","{TYPE}/{SUBTYPE}; q={NUMBER_0TO1}")
ctx.rule("MEDIA_RANGE","{MEDIA_RANGE}, {MEDIA_RANGE}")
ctx.rule("TYPE","audio")
ctx.rule("TYPE","*")
ctx.rule("TYPE","video")
ctx.rule("TYPE","image")
ctx.rule("TYPE","text")
ctx.rule("SUBTYPE","*")
ctx.rule("SUBTYPE","plain")
ctx.rule("SUBTYPE","html")
ctx.rule("SUBTYPE","basic")
ctx.rule("SUBTYPE","x-dvi")
ctx.rule("SUBTYPE","x-c")
ctx.rule("ACCEPT_CHARSET","")
ctx.rule("ACCEPT_CHARSET","Accept-Charset: {CHARSET2}\n")
ctx.rule("CHARSET2","{CHARSET} ;q={NUMBER_0TO1}")
ctx.rule("CHARSET2","{CHARSET2}, {CHARSET2}")
ctx.rule("CHARSET2","{CHARSET}")
ctx.rule("CHARSET","US-ASCII")
ctx.rule("CHARSET","ISO-8859-1")
ctx.rule("CHARSET","ISO-8859-2")
ctx.rule("CHARSET","ISO-8859-3")
ctx.rule("CHARSET","ISO-8859-4")
ctx.rule("CHARSET","ISO-8859-5")
ctx.rule("CHARSET","ISO-8859-6")
ctx.rule("CHARSET","ISO-8859-7")
ctx.rule("CHARSET","ISO-8859-8")
ctx.rule("CHARSET","ISO-8859-9")
ctx.rule("CHARSET","ISO-8859-10")
ctx.rule("CHARSET","Shift_JIS")
ctx.rule("CHARSET","EUC-JP")
ctx.rule("CHARSET","ISO-8859-6-E")
ctx.rule("CHARSET","ISO-8859-6-I")
ctx.rule("CHARSET","ISO-8859-8-I")
ctx.rule("CHARSET","ISO-8859-8-E")
ctx.rule("ACCEPT_ENCODING","")
ctx.rule("ACCEPT_ENCODING","Accept-Encoding: {ENCODING}\n")
ctx.rule("ENCODING","{ENCODING}, {ENCODING}")
ctx.rule("ENCODING","{CODE_ENCODING}")
ctx.rule("ENCODING","{CODE_ENCODING}; q={NUMBER_0TO1}")
ctx.rule("CODE_ENCODING","compress")
ctx.rule("CODE_ENCODING","gzip")
ctx.rule("CODE_ENCODING","compress")
ctx.rule("CODE_ENCODING","*")
ctx.rule("CODE_ENCODING","identity")
ctx.rule("ACCEPT_LANGUAGE","")
ctx.rule("ACCEPT_LANGUAGE","Accept-Language: {LANGUAGE}\n")
ctx.rule("LANGUAGE","{LANGUAGE}, {LANGUAGE}")
ctx.rule("LANGUAGE","{LAN}-{LAN}; q={NUMBER_0TO1}")
ctx.rule("LANGUAGE","{LAN}; q={NUMBER_0TO1}")
ctx.rule("LANGUAGE","{LAN}")
ctx.rule("LAN","ab")
ctx.rule("LAN","aa")
ctx.rule("LAN","af")
ctx.rule("LAN","ak")
ctx.rule("LAN","sq")
ctx.rule("LAN","am")
ctx.rule("LAN","ar")
ctx.rule("LAN","an")
ctx.rule("LAN","hy")
ctx.rule("LAN","as")
ctx.rule("LAN","av")
ctx.rule("LAN","ae")
ctx.rule("LAN","ay")
ctx.rule("LAN","az")
ctx.rule("LAN","bm")
ctx.rule("LAN","ba")
ctx.rule("LAN","eu")
ctx.rule("LAN","be")
ctx.rule("LAN","bn")
ctx.rule("LAN","bh")
ctx.rule("LAN","bi")
ctx.rule("LAN","bs")
ctx.rule("LAN","br")
ctx.rule("LAN","bg")
ctx.rule("LAN","my")
ctx.rule("LAN","ca")
ctx.rule("LAN","ch")
ctx.rule("LAN","ce")
ctx.rule("LAN","ny")
ctx.rule("LAN","zh")
ctx.rule("LAN","cv")
ctx.rule("LAN","kw")
ctx.rule("LAN","co")
ctx.rule("LAN","cr")
ctx.rule("LAN","hr")
ctx.rule("LAN","cs")
ctx.rule("LAN","da")
ctx.rule("LAN","dv")
ctx.rule("LAN","nl")
ctx.rule("LAN","dz")
ctx.rule("LAN","en")
ctx.rule("LAN","eo")
ctx.rule("LAN","et")
ctx.rule("LAN","ee")
ctx.rule("LAN","fo")
ctx.rule("LAN","fj")
ctx.rule("LAN","fi")
ctx.rule("LAN","fr")
ctx.rule("LAN","ff")
ctx.rule("LAN","gl")
ctx.rule("LAN","gd")
ctx.rule("LAN","gv")
ctx.rule("LAN","ka")
ctx.rule("LAN","de")
ctx.rule("LAN","el")
ctx.rule("LAN","kl")
ctx.rule("LAN","gn")
ctx.rule("LAN","gu")
ctx.rule("LAN","ht")
ctx.rule("LAN","ha")
ctx.rule("LAN","he")
ctx.rule("LAN","hz")
ctx.rule("LAN","hi")
ctx.rule("LAN","ho")
ctx.rule("LAN","hu")
ctx.rule("LAN","is")
ctx.rule("LAN","io")
ctx.rule("LAN","ig")
ctx.rule("LAN","in")
ctx.rule("LAN","ia")
ctx.rule("LAN","ie")
ctx.rule("LAN","iu")
ctx.rule("LAN","ik")
ctx.rule("LAN","ga")
ctx.rule("LAN","it")
ctx.rule("LAN","ja")
ctx.rule("LAN","jv")
ctx.rule("LAN","kl")
ctx.rule("LAN","kn")
ctx.rule("LAN","kr")
ctx.rule("LAN","ks")
ctx.rule("LAN","kk")
ctx.rule("LAN","km")
ctx.rule("LAN","ki")
ctx.rule("LAN","rw")
ctx.rule("LAN","rn")
ctx.rule("LAN","ky")
ctx.rule("LAN","kv")
ctx.rule("LAN","kg")
ctx.rule("LAN","ko")
ctx.rule("LAN","ku")
ctx.rule("LAN","kj")
ctx.rule("LAN","lo")
ctx.rule("LAN","la")
ctx.rule("LAN","lv")
ctx.rule("LAN","li")
ctx.rule("LAN","ln")
ctx.rule("LAN","lt")
ctx.rule("LAN","lu")
ctx.rule("LAN","lg")
ctx.rule("LAN","lb")
ctx.rule("LAN","gv")
ctx.rule("LAN","mk")
ctx.rule("LAN","mg")
ctx.rule("LAN","ms")
ctx.rule("LAN","ml")
ctx.rule("LAN","mt")
ctx.rule("LAN","mi")
ctx.rule("LAN","mr")
ctx.rule("LAN","mh")
ctx.rule("LAN","mo")
ctx.rule("LAN","mn")
ctx.rule("LAN","na")
ctx.rule("LAN","nv")
ctx.rule("LAN","ng")
ctx.rule("LAN","nd")
ctx.rule("LAN","ne")
ctx.rule("LAN","no")
ctx.rule("LAN","nb")
ctx.rule("LAN","nn")
ctx.rule("LAN","ii")
ctx.rule("LAN","oc")
ctx.rule("LAN","oj")
ctx.rule("LAN","cu")
ctx.rule("LAN","or")
ctx.rule("LAN","om")
ctx.rule("LAN","os")
ctx.rule("LAN","pi")
ctx.rule("LAN","ps")
ctx.rule("LAN","fa")
ctx.rule("LAN","pl")
ctx.rule("LAN","pt")
ctx.rule("LAN","pa")
ctx.rule("LAN","qu")
ctx.rule("LAN","rm")
ctx.rule("LAN","ro")
ctx.rule("LAN","ru")
ctx.rule("LAN","se")
ctx.rule("LAN","sm")
ctx.rule("LAN","sg")
ctx.rule("LAN","sa")
ctx.rule("LAN","sr")
ctx.rule("LAN","sh")
ctx.rule("LAN","st")
ctx.rule("LAN","tn")
ctx.rule("LAN","sn")
ctx.rule("LAN","ii")
ctx.rule("LAN","sd")
ctx.rule("LAN","si")
ctx.rule("LAN","ss")
ctx.rule("LAN","sk")
ctx.rule("LAN","sl")
ctx.rule("LAN","so")
ctx.rule("LAN","nr")
ctx.rule("LAN","es")
ctx.rule("LAN","su")
ctx.rule("LAN","sw")
ctx.rule("LAN","ss")
ctx.rule("LAN","sv")
ctx.rule("LAN","tl")
ctx.rule("LAN","ty")
ctx.rule("LAN","tg")
ctx.rule("LAN","ta")
ctx.rule("LAN","tt")
ctx.rule("LAN","te")
ctx.rule("LAN","th")
ctx.rule("LAN","bo")
ctx.rule("LAN","ti")
ctx.rule("LAN","to")
ctx.rule("LAN","ts")
ctx.rule("LAN","tr")
ctx.rule("LAN","tk")
ctx.rule("LAN","tw")
ctx.rule("LAN","ug")
ctx.rule("LAN","uk")
ctx.rule("LAN","ur")
ctx.rule("LAN","uz")
ctx.rule("LAN","ve")
ctx.rule("LAN","vi")
ctx.rule("LAN","vo")
ctx.rule("LAN","wa")
ctx.rule("LAN","cy")
ctx.rule("LAN","wo")
ctx.rule("LAN","fy")
ctx.rule("LAN","xh")
ctx.rule("LAN","yi")
ctx.rule("LAN","yo")
ctx.rule("LAN","za")
ctx.rule("LAN","zu")
ctx.rule("LAN","id")
ctx.rule("LAN","ji")
ctx.rule("LAN","org")
ctx.rule("LAN","net")
ctx.rule("LAN","onion")
ctx.rule("AUTHORIZATION","")
ctx.rule("AUTHORIZATION","Authorization: {ATYPE} {STRING}\n")
ctx.rule("ATYPE","Basic")
ctx.rule("ATYPE","Bearer")
ctx.rule("ATYPE","Digest")
ctx.rule("ATYPE","HOBA")
ctx.rule("ATYPE","Mutual")
ctx.rule("ATYPE","Negotiate")
ctx.rule("ATYPE","OAuth")
ctx.rule("ATYPE","SCRAM-SHA-1")
ctx.rule("ATYPE","SCRAM-SHA-256")
ctx.rule("ATYPE","vapid")
ctx.rule("ATYPE","")
ctx.rule("EXPECT","")
ctx.rule("EXPECT","Expect: 100-continue\n")
ctx.rule("FROM","")
ctx.rule("FROM","From: {MAILADDRESS}\n")
ctx.rule("MAILADDRESS","{LOWSTRING}@{LOWSTRING}.{LAN}")
ctx.rule("HOST","")
ctx.rule("HOST","Host: {IP}\n")
ctx.rule("HOST","Host: www.{STRING}.{LAN}\n")
ctx.rule("IF_MATCH","")
ctx.rule("IF_MATCH","If-Match: {ENTITY_TAG2}\n")
ctx.rule("IF_MATCH","If-None-Match: {ENTITY_TAG2}\n")
ctx.rule("IF_MATCH","If-Range: {ENTITY_TAG2}\n")
ctx.rule("ENTITY_TAG2","{ENTITY_TAG2}, {ENTITY_TAG}")
ctx.rule("ENTITY_TAG2","{ENTITY_TAG}")
ctx.rule("ENTITY_TAG2","*")
ctx.rule("ENTITY_TAG",'"{TAG}"')
ctx.rule("IF_MODIFIED_SINCE","")
ctx.rule("IF_MODIFIED_SINCE","If-Modified-Since: {HTTP_DATE}\n")
ctx.rule("IF_MODIFIED_SINCE","If-Range: {HTTP_DATE}\n")
ctx.rule("IF_MODIFIED_SINCE","If-Unmodified-Since: {HTTP_DATE}\n")
ctx.rule("MAX_FORWARDS","")
ctx.rule("MAX_FORWARDS","Max-Forwards: {NUMBER}\n")
ctx.rule("PROXY_AUTHORIZATION","")
ctx.rule("PROXY_AUTHORIZATION","Proxy-Authorization: {ATYPE} {STRING}\n")
ctx.rule("RANGE","")
ctx.rule("RANGE","Range: {NUMBERPOS}-{NUMBERPOS}\n")
ctx.rule("RANGE","Range: -{NUMBERPOS}\n")
ctx.rule("RANGE","Range: {NUMBERPOS}-\n")
ctx.rule("REFERER","")
ctx.rule("REFERER","Referer: {REQUEST_URI}\n")
ctx.rule("TE","")
ctx.rule("TE","TE: trailers\n")
ctx.rule("TE","TE: deflate\n")
ctx.rule("TE","TE: trailers, deflate;q={NUMBER_0TO1}\n")
ctx.rule("USER_AGENT","")
ctx.rule("USER_AGENT","User-Agent: {PRODUCT}\n")
